### ISSUE TITLE
Underage Redirect

### ISSUE THREAD

**Issue by pixelsalsa** [SpecialKcl/jQuery-Age-Gate-Plugin#1]
I have the underage message working but not the redirect - how do i ensure this works?

**Comment by KaiHotz** [comment]
Actually i stoped  maintaining this for quite a while now,  but anyhow, if you are using this you should have your local server up and running. Te redirect should work out of the box since it sets the url via `window.location.href ` to the `underage_url` or `site_url`. This was developed a long time ago for educational purposes an is not meant to be used in production
